import Head from 'next/head'

import { useEffect, useState } from 'react';

import App from '@/components/App'
import Config from '@/components/Config'

const backendUrl = Config.urlPrefix;

export default function Home() {
  const [metadata, setMetadata] = useState(null);

  useEffect(() => {
    fetch(backendUrl + "/metadata", {credentials: "include"})
      .then(r => {
        if(r.status === 401)
          window.location.replace("/login");
        return r.json()
      }).then(metadata => {
        metadata.locations.sort((a, b) => a.properties.id - b.properties.id);
        metadata.grid = metadata.locations;
        metadata.measurements = metadata.metrics;
        metadata.parishesMapping = metadata.parishes;
        setMetadata(metadata);
      });
  }, []);

  return (
    <>
      <Head>
        <title>Crowding Visualization</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link href='https://unpkg.com/maplibre-gl@2.4.0/dist/maplibre-gl.css' rel='stylesheet' />
      </Head>
      <main>
        <div style={{
          position: "fixed",
          top: 0,
          left: 0,
          right: 0,
          bottom: 0}}>
          {metadata ?
            <App {...metadata} />
          : <p>Loading app...</p>}
        </div>
      </main>
    </>
  )
}
