import Head from 'next/head'

import { useState } from 'react';

import TextField from '@mui/material/TextField';
import Button from '@mui/material/Button';
import Alert from '@mui/material/Alert';
import Stack from '@mui/material/Stack';
import Typography from '@mui/material/Typography';

import config from '@/components/Config';

export default function Login(props) {
  const [email, setEmail] = useState("");
  const [alert, setAlert] = useState(null);
  const [disabled, setDisabled] = useState(false);
  const [done, setDone] = useState(false);

  function action() {
    setDisabled(true);
    fetch(config.urlPrefix + "/auth/forgot_password", {method: "POST", headers: {"Content-Type": "application/json"}, body: JSON.stringify({email})})
      .then(r => {
        if(r.status === 200) {
          setDone(true);
        } else {
          setAlert("Unexpected error");
          setDisabled(false);
        }
      });
  }

  return (
    <>
      <Head>
        <title>Crowding Visualization</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {!done ?
            <>
                <Stack spacing={2}>
                <TextField label="Email" value={email} onChange={e => setEmail(e.target.value)} />
                <Button disabled={disabled} variant="contained" onClick={action}>Reset password</Button>
                </Stack>
                {alert && <Alert severity="error" onClose={() => setAlert(null)}>{alert}</Alert>}
            </>
            : <Typography>Reactivation link sent to {email}</Typography>}
      </main>
    </>
  )
}
