import Head from 'next/head'

export default function Home(props) {
  return (
    <>
      <Head>
        <title>Crowding Visualization</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <p><a href="/vodafone">Vodafone</a></p>
        <p><a href="/iscte">ISCTE</a></p>
        <p><a href="/melbourne">Melbourne</a></p>
      </main>
    </>
  )
}
