import Head from 'next/head'

export default function Home(props) {
  if(typeof window !== 'undefined')
    window.location.replace("/vodafone");

  return (
    <>
      <Head>
        <title>Crowding Visualization</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </>
  )
}
