connector: opendatasoft
connector_parameters:
  url: https://data.melbourne.vic.gov.au/api/v2
  dataset: pedestrian-counting-system-past-hour-counts-per-minute
  timestamp_field: sensing_datetime
  location_field: location_id
  metric_field: total_of_directions
  ignore_before: 1w

influxdb_parameters:
  url: <INFLUXDB_URL>
  token: <INFLUXDB_TOKEN>
  org: <INFLUXDB_ORG>
  bucket: <INFLUXDB_BUCKET>

fetch_from: "2024-06-01T00:00:00+00:00" # isoformat datetime (offset aware)
mode: "live"
polling_interval: 300 # seconds
